arch: amd64
os: linux
dist: focal

language: c

compiler: gcc



install:
  - sudo apt-get install valgrind
  - sudo apt-get install cppcheck
  - sudo pip install cpplint

script:
  - cppcheck --enable=all --language=c tf_idf_lib/include/*.h tf_idf_lib/source/*.c --suppress=missingInclude
  - cpplint --extensions=c tf_idf_lib/include/* tf_idf_lib/source/*
  - mkdir build && cd build
  - cmake ..  
  - make clean && make
  - pwd
  - valgrind --tool=memcheck --leak-check=full ctest
  - cd ../data/test-1
  - ls

after_success:
  - bash <(curl -s https://codecov.io/bash)